//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ShippingAddress { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual User User { get; set; }
    }
    public  class OrderRequest
    {
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ShippingAddress { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int OrderId { get; set; }
    }

    public  class UpdateOrderRequest
    {
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Status { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ItemId { get; set; }
        public int ProductId { get; set; }

    }
}
