//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> Height { get; set; }
        public string ImageId { get; set; }
        public Nullable<int> stockkeepingUnit { get; set; }
        public Nullable<long> barcode { get; set; }
        public Nullable<int> Availablequantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
